### ISSUE TITLE
blog.html produces errors in Google's Structured Data Testing Tool

### ISSUE THREAD

**Issue by FunkyLoveCow** [philwareham/schema-microdata-examples#2]
When checking the validity of [blog.html](https://github.com/philwareham/schema-microdata-examples/blob/master/blog.html) in Google's Structured Data Testing Tool, the `BlogPosting` sections contain multiple errors:

![Multiple Errors](https://i.imgur.com/5tmhJIE.png)

The details of these errors include:

 - Missing Author
 - Missing Date published
 - Missing Image
 - Missing Publisher
 - Warning: Missing modified date

![Error Details](https://i.imgur.com/qigvL80.png)

**Comment by philwareham** [comment]
Thanks. The latest commit fixes these validation errors.
